config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      get 'start', as: :start
      get 'complete', as: :complete
      get 'uncomplete', as: :uncomplete
      get 'unstart', as: :unstart
      get 'archive', as: :archive
    end
  end
  resources :colors

  get '/taskhistory' => 'task_histories#index', as: :task_history
  get '/magic' => 'task_histories#magic', as: :magic

end

app/models/task.rb
class Task < ApplicationRecord
  has_many :task_histories
  belongs_to :color

  enum status: [:not_started, :in_progress, :completed, :archived]

  # alias class method through so editors can stop being mad about "method not exist"
  # noinspection RubyResolve
  class <<self
    # alias colors colors
    alias statuses statuses
  end

  validates :status, inclusion: {in: statuses.keys}

  before_validation :set_default_status

  after_create :log_hist
  after_update :log_hist

  def set_default_status
    if self.status.nil?
      self.status = :not_started
    end
  end

  def log_hist
    TaskHistory.create!(description: description, color_id: color_id, status: status, task: self)
  end

  # region actions {{{
  def start
    if status.to_sym.eql? :not_started
      update!(status: :in_progress)
    else
      false
    end
  end

  def complete
    if status.to_sym.eql? :in_progress
      update!(status: :completed)
    else
      false
    end
  end

  def unstart
    if status.to_sym.eql? :in_progress
      update!(status: :not_started)
    else
      false
    end
  end

  def uncomplete
    if status.to_sym.eql? :completed
      update!(status: :in_progress)
    else
      false
    end
  end

  def archive
    update!(status: :archived)
  end
  # }}} endregion actions
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :start, :complete, :uncomplete, :unstart, :archive, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tasks/1/start
  def start
    respond_to do |format|
      if @task.start
        format.html { redirect_to tasks_url }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tasks/1/complete
  def complete
    respond_to do |format|
      if @task.complete
        format.html { redirect_to tasks_url }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tasks/1/uncomplete
  def uncomplete
    respond_to do |format|
      if @task.uncomplete
        format.html { redirect_to tasks_url }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tasks/1/unstart
  def unstart
    respond_to do |format|
      if @task.unstart
        format.html { redirect_to tasks_url }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /tasks/1/archive
  def archive
    respond_to do |format|
      if @task.archive
        format.html { redirect_to tasks_url }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :color_id, :status)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>

    <% if task.errors.any? %>
        <p class="alert-warning"><%= task.errors.as_json %></p>
    <% end %>

    <div class="field row">
      <div class="col-xs-2 col-form-label-sm">
        <%= f.label :description, 'description:' %>
      </div>
      <div class="col-xs-4">
        <%= f.text_area :description %>
      </div>
    </div>

    <div class="field row">
      <div class="col-xs-2 col-form-label-sm">
        <%= f.label :color_id, 'color:' %>
      </div>
      <div class="col-xs-4">
        <%= f.select :color_id do %>
            <% Color.all.each do |color| %>
                <%= content_tag(:option, color.to_s, value: color.id, class: color.name, selected: (color.eql? task.color)) %>
            <% end %>
        <% end %>
      </div>
    </div>

    <div class="actions row">
      <div class="col-xs-4 offset-xs-2">
        <%= f.submit (task.persisted? ? 'update task' : 'create task') %>
      </div>
    </div>
<% end %>

app/views/tasks/_task.erb
<a href="<%= edit_task_path(task) %>">
  <div class="card">
    <div class="card-block <%= task.color %>">
      <div class="col-xs-8">
        <p class="card-text"><%= task.description %></p>
      </div>
      <div class="col-xs-4">
        <% if task.errors.any? %>
          <p><%= task.errors.as_json %></p>
        <% end %>
        <% if task.status.to_sym.eql? :not_started %>
            <%= link_to 'start', start_task_url(task), class: 'card-link' %>
        <% elsif task.status.to_sym.eql? :in_progress %>
            <%= link_to 'unstart', unstart_task_url(task), class: 'card-link' %>
            <br>
            <%= link_to 'complete', complete_task_url(task), class: 'card-link' %>
        <% elsif task.status.to_sym.eql? :completed %>
            <%= link_to 'uncomplete', uncomplete_task_url(task), class: 'card-link' %>
        <% end %>
      </div>
    </div>
  </div>
</a>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= render 'form', task: @task %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 offset-md-2">
      <%= button_to 'archive', archive_task_url(@task), method: :get %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">

  <div class="row">
    <p id="notice"><%= notice %></p>
  </div>

  <div class="col-lg-4">
    <h4>not started</h4>
    <%= render @tasks.where(status: :not_started) %>
  </div>

  <div class="col-lg-4">
    <h4>in progress</h4>
    <%= render @tasks.where(status: :in_progress) %>
  </div>

  <div class="col-lg-4">
    <h4>completed</h4>
    <%= render @tasks.where(status: :completed) %>
  </div>

</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= render 'form', task: @task %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <% if notice %>
      <div class="alert alert-dismissible">
        <p id="notice"><%= notice %></p>
      </div>
  <% end %>
  <div class="row">
    <div class="col-xs-2">
      <p>description:</p>
    </div>
    <div class="col-xs-4">
      <p><%= @task.description %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2">
      <p>color:</p>
    </div>
    <div class="col-xs-4">
      <p><%= @task.color %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-2">
      <p>status:</p>
    </div>
    <div class="col-xs-4">
      <p><%= @task.status.humanize.downcase %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-4 offset-xs-2">
      <%= link_to 'edit', edit_task_path(@task) %>
    </div>
  </div>
</div>