config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    member do
      get 'start', as: :start
      get 'complete', as: :complete
      get 'uncomplete', as: :uncomplete
      get 'unstart', as: :unstart
      get 'archive', as: :archive
    end
  end
  resources :colors

  get '/taskhistory' => 'task_histories#index', as: :task_history
  get '/magic' => 'task_histories#magic', as: :magic

end

app/models/task_history.rb
class TaskHistory < ApplicationRecord
  belongs_to :task

  enum status: [:not_started, :in_progress, :completed, :archived]

  # alias class method through so editors can stop being mad about "method not exist"
  # noinspection RubyResolve
  class <<self
    alias statuses statuses
  end

  validates :status, inclusion: {in: statuses.keys}


end

app/controllers/task_histories_controller.rb
class TaskHistoriesController < ApplicationController

  def index
    @task_histories = TaskHistory.all.order(:created_at).reverse
  end

  def magic
    # ActiveRecordModel.joins - how do you work?
    history_groups = TaskHistory.where(task: Task.where.not(status: :archived)).group_by(&:task)

    @time_pending_by_task = {}

    history_groups.each { |task, hist_records|
      @time_pending_by_task[task] = 0
      hist_records.sort_by { |record| record[:id] }
      last_action_was_to_in_progress = false
      last_start_progress = nil
      hist_records.each { |record|
        if record.status.to_sym.eql? :in_progress
          unless last_action_was_to_in_progress
            last_action_was_to_in_progress = true
            last_start_progress = record.created_at
          end
        else
          if last_action_was_to_in_progress
            @time_pending_by_task[task] += (record.created_at - last_start_progress)
          end
          last_action_was_to_in_progress = false
        end
      }
      if last_action_was_to_in_progress
        @time_pending_by_task[task] += Time.now - last_start_progress
      end
    }

    @time_pending_by_task = Hash[@time_pending_by_task.sort_by { |_, v| v }.reverse]
  end
end

app/helpers/task_histories_helper.rb
module TaskHistoriesHelper
end

app/helpers/taskhistory_helper.rb
module TaskhistoryHelper
end

app/views/task_histories/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <p><%= link_to 'magic algorithm to sort by tasks that have been pending for a long time', magic_url %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <% @task_histories.each do |hist_record| %>
          <div class="row">
            <p><%= hist_record.created_at.in_time_zone('Central Time (US & Canada)').strftime('%m/%d %I:%M%p') %></p>
          </div>
      <% end %>
    </div>
  </div>

</div>

app/views/task_histories/magic.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-12">
      <p style="margin-bottom: 50px;">This report shows unarchived tasks that have taken a long time. You should strive to work on things that
        have been in progress for a long time, lest they weigh more and more on your other tasks.</p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-xs-6">
          <h4>task</h4>
        </div>
        <div class="col-xs-4">
          <h4>time in progress</h4>
        </div>
      </div>
      <% @time_pending_by_task.each do |key, value| %>
          <div class="row">
            <div class="col-xs-6">
              <%= render key %>
            </div>
            <div class="col-xs-4">
              <p><%= "#{(value / 60).round}" %> minutes in progress.</p>
            </div>
          </div>
      <% end %>
    </div>
  </div>

</div>